/**
 * Network Automation & Subnet Console - Cisco CLI Generator Logic
 * 
 * ไฟล์นี้ทำหน้าที่เป็น Template Engine เพื่อสร้างสคริปต์คำสั่ง Cisco CLI
 * สำหรับสวิตช์และเราเตอร์ โดยดึงข้อมูลจากตาราง VLAN และผลลัพธ์คณิตศาสตร์เครือข่าย
 */

/**
 * สร้างชุดสคริปต์คำสั่ง Cisco IOS CLI จากพารามิเตอร์ที่กำหนด
 * @param {Object} options - พารามิเตอร์การตั้งค่าอุปกรณ์
 * @param {string} options.hostname - ชื่อโฮสต์ของอุปกรณ์
 * @param {string} options.enableSecret - รหัสผ่านเข้าโหมด Privileged EXEC
 * @param {string} options.bannerMotd - ข้อความแสดงความยินดี/แจ้งเตือนเมื่อเข้าระบบ
 * @param {boolean} options.enableSsh - เปิดใช้งานการเข้าถึงระยะไกลด้วย SSH หรือไม่
 * @param {string} options.portType - ประเภทพอร์ตเริ่มต้น เช่น FastEthernet, GigabitEthernet
 * @param {Array} options.vlans - รายการ VLAN ที่ต้องการตั้งค่า
 * @returns {string} สคริปต์คำสั่ง Cisco CLI ที่จัดรูปแบบแล้ว
 */
function generateCiscoConfig(options) {
    const { 
        hostname, 
        enableSecret, 
        bannerMotd, 
        enableSsh, 
        portType, 
        vlans,
        deviceRole = "L3_Core_Switch",
        hwModel = "Catalyst 9300",
        routerConfig = {},
        disableDns = true
    } = options;
    const lines = [];

    // Helper: คำนวณ Wildcard Mask จาก Subnet Mask
    function getWildcardMask(subnetMask) {
        return subnetMask.split('.').map(octet => 255 - parseInt(octet, 10)).join('.');
    }

    // หัวสคริปต์ระบุข้อมูลผู้ใช้และระบบ
    const displayRole = deviceRole.replace(/_/g, " ");
    lines.push("! ==================================================");
    lines.push("! Cisco IOS Config Generated by NET-AUTO.OS v1.3");
    lines.push(`! Device Role: ${displayRole} // Model: ${hwModel}`);
    lines.push("! DevNode: 68319010053 // SysAdmin: SUPAKORN P.");
    lines.push(`! Generated: ${new Date().toISOString().replace('T', ' ').substring(0, 19)} UTC`);
    lines.push("! Note: Ensure you are in configure terminal mode before pasting.");
    lines.push("! ==================================================");
    lines.push("");

    // 1. ตั้งค่าพื้นฐานระดับ Global: Hostname
    if (hostname && hostname.trim() !== "") {
        lines.push("! --- Global System Name ---");
        lines.push(`hostname ${hostname.trim()}`);
        lines.push("");
    }

    // 1.5 ปิด IP Domain Lookup
    if (disableDns) {
        lines.push("! --- Disable IP Domain Lookup ---");
        lines.push("no ip domain-lookup");
        lines.push("");
    }

    // 2. ตั้งค่าความปลอดภัยระดับ Privileged EXEC: Enable Secret
    if (enableSecret && enableSecret.trim() !== "") {
        lines.push("! --- Privilege Mode Protection ---");
        lines.push(`enable secret ${enableSecret.trim()}`);
        lines.push("");
    }

    // 3. ตั้งค่า Banner MOTD
    if (bannerMotd && bannerMotd.trim() !== "") {
        lines.push("! --- Banner Message of The Day ---");
        lines.push("banner motd ^");
        lines.push(bannerMotd.trim());
        lines.push("^");
        lines.push("");
    }

    // 4. ตั้งค่าบริการ SSH & VTY Sec
    if (enableSsh) {
        lines.push("! --- SSH & Management Protection ---");
        lines.push("ip domain-name netauto.local");
        lines.push("crypto key generate rsa general-keys modulus 2048");
        lines.push("ip ssh version 2");
        lines.push("ip ssh time-out 60");
        lines.push("ip ssh authentication-retries 3");
        lines.push("");
        lines.push("line vty 0 4");
        lines.push("  transport input ssh");
        lines.push("  login local");
        lines.push("  exec-timeout 15 0");
        lines.push("exit");
        lines.push("");
    }

    // แยกการทำงานตาม Device Role
    if (deviceRole === "Edge_Router") {
        // --- EDGE ROUTER CONFIGURATION ---
        const {
            wanIf = "GigabitEthernet0/0/0",
            wanIp = "10.0.0.2",
            wanCidr = 30,
            wanGw = "10.0.0.1",
            lanIf = "GigabitEthernet0/0/1",
            lanIp = "192.168.1.1",
            lanCidr = 24,
            ospfPid = 1,
            ospfArea = 0,
            enableOspf = true,
            enableNat = true,
            blockSsh = true
        } = routerConfig;

        lines.push("! --- Router Interfaces Configuration ---");

        // WAN Interface Config
        let wanNetmask = "255.255.255.252";
        let wanNetwork = "10.0.0.0";
        if (window.NetSubnet) {
            try {
                const res = window.NetSubnet.calculateSubnet(wanIp, wanCidr);
                wanNetmask = res.subnetMask;
                wanNetwork = res.networkAddress;
            } catch (e) {
                console.error("WAN Subnet calculation failed", e);
            }
        }
        lines.push(`interface ${wanIf}`);
        lines.push("  description WAN Uplink Connection");
        lines.push(`  ip address ${wanIp} ${wanNetmask}`);
        if (enableNat) {
            lines.push("  ip nat outside");
        }
        if (blockSsh) {
            lines.push("  ip access-group 100 in");
        }
        lines.push("  no shutdown");
        lines.push("exit");
        lines.push("");

        // LAN Interface Config
        let lanNetmask = "255.255.255.0";
        let lanNetwork = "192.168.1.0";
        if (window.NetSubnet) {
            try {
                const res = window.NetSubnet.calculateSubnet(lanIp, lanCidr);
                lanNetmask = res.subnetMask;
                lanNetwork = res.networkAddress;
            } catch (e) {
                console.error("LAN Subnet calculation failed", e);
            }
        }
        lines.push(`interface ${lanIf}`);
        lines.push("  description LAN Internal Network Gateway");
        lines.push(`  ip address ${lanIp} ${lanNetmask}`);
        if (enableNat) {
            lines.push("  ip nat inside");
        }
        lines.push("  no shutdown");
        lines.push("exit");
        lines.push("");

        // Basic WAN Firewall (ACLs)
        if (blockSsh) {
            lines.push("! --- Basic WAN Firewall (Block External SSH/Telnet) ---");
            lines.push("access-list 100 deny tcp any any eq 22");
            lines.push("access-list 100 deny tcp any any eq 23");
            lines.push("access-list 100 permit ip any any");
            lines.push("");
        }

        // NAT PAT Configurations
        if (enableNat) {
            lines.push("! --- Dynamic NAT/PAT Engine (PAT Overload) ---");
            const lanWildcard = getWildcardMask(lanNetmask);
            lines.push(`access-list 1 permit ${lanNetwork} ${lanWildcard}`);
            lines.push(`ip nat inside source list 1 interface ${wanIf} overload`);
            lines.push("");
        }

        // OSPF Routing Configurations
        if (enableOspf) {
            lines.push("! --- OSPF Dynamic Routing Engine ---");
            lines.push(`router ospf ${ospfPid}`);
            const wanWildcard = getWildcardMask(wanNetmask);
            const lanWildcard = getWildcardMask(lanNetmask);
            lines.push(`  network ${wanNetwork} ${wanWildcard} area ${ospfArea}`);
            lines.push(`  network ${lanNetwork} ${lanWildcard} area ${ospfArea}`);
            lines.push("exit");
            lines.push("");
        }

        // Static Route Configuration
        if (wanGw && wanGw.trim() !== "") {
            lines.push("! --- Default Static Route to ISP ---");
            lines.push(`ip route 0.0.0.0 0.0.0.0 ${wanGw.trim()}`);
            lines.push("");
        }

    } else if (deviceRole === "L2_Access_Switch") {
        // --- L2 ACCESS SWITCH CONFIGURATION ---
        lines.push("! --- Layer 2 Core Setting (Routing Disabled) ---");
        lines.push("no ip routing");
        lines.push("");

        if (vlans && vlans.length > 0) {
            lines.push("! --- VLAN Database Creation ---");
            vlans.forEach(vlan => {
                lines.push(`vlan ${vlan.id}`);
                lines.push(`  name ${vlan.name}`);
                lines.push("exit");
            });
            lines.push("");

            lines.push("! --- Switchport Port Allocations ---");
            vlans.forEach(vlan => {
                if (vlan.portRange && vlan.portRange.trim() !== "") {
                    const cleanPortType = portType || "FastEthernet";
                    lines.push(`! Assign ports range ${cleanPortType} ${vlan.portRange.trim()} to VLAN ${vlan.id}`);
                    lines.push(`interface range ${cleanPortType} ${vlan.portRange.trim()}`);
                    lines.push("  switchport mode access");
                    lines.push(`  switchport access vlan ${vlan.id}`);
                    lines.push("  no shutdown");
                    lines.push("exit");
                    lines.push("");
                }
            });
        }
    } else {
        // --- L3 CORE SWITCH CONFIGURATION (Default Mode) ---
        if (vlans && vlans.length > 0) {
            lines.push("! --- VLAN Database Creation ---");
            vlans.forEach(vlan => {
                lines.push(`vlan ${vlan.id}`);
                lines.push(`  name ${vlan.name}`);
                lines.push("exit");
            });
            lines.push("");

            // เปิดใช้งาน Routing สำหรับ Inter-VLAN Routing (Layer 3 Switch routing)
            lines.push("! --- Layer 3 Routing Enable ---");
            lines.push("ip routing");
            lines.push("");

            // SVI, Ports และ DHCP
            lines.push("! --- SVI Interfaces & DHCP Scope Allocations ---");
            vlans.forEach(vlan => {
                lines.push(`! ==================== VLAN ${vlan.id} [${vlan.name}] ====================`);
                
                let netmask = "255.255.255.0";
                let networkAddr = "";
                
                if (window.NetSubnet) {
                    try {
                        const result = window.NetSubnet.calculateSubnet(vlan.ip, vlan.cidr);
                        netmask = result.subnetMask;
                        networkAddr = result.networkAddress;
                    } catch (err) {
                        console.error(`Subnet calculation failed for VLAN ${vlan.id}:`, err);
                    }
                }

                // SVI Config
                lines.push(`interface vlan ${vlan.id}`);
                lines.push(`  description SVI Gateway for ${vlan.name}`);
                lines.push(`  ip address ${vlan.ip} ${netmask}`);
                lines.push("  no shutdown");
                lines.push("exit");
                lines.push("");

                // Physical port allocation
                if (vlan.portRange && vlan.portRange.trim() !== "") {
                    const cleanPortType = portType || "FastEthernet";
                    lines.push(`! Assign ports range ${cleanPortType} ${vlan.portRange.trim()} to VLAN ${vlan.id}`);
                    lines.push(`interface range ${cleanPortType} ${vlan.portRange.trim()}`);
                    lines.push("  switchport mode access");
                    lines.push(`  switchport access vlan ${vlan.id}`);
                    lines.push("  no shutdown");
                    lines.push("exit");
                    lines.push("");
                }

                // DHCP scopes
                if (vlan.dhcp && networkAddr !== "") {
                    lines.push(`! DHCP Scope for VLAN ${vlan.id}`);
                    lines.push(`ip dhcp excluded-address ${vlan.ip}`);
                    lines.push(`ip dhcp pool VLAN_${vlan.id}_POOL`);
                    lines.push(`  network ${networkAddr} ${netmask}`);
                    lines.push(`  default-router ${vlan.ip}`);
                    lines.push("  dns-server 8.8.8.8");
                    lines.push("exit");
                    lines.push("");
                }
            });
        }
    }

    // ท้ายสคริปต์บันทึกค่าลงหน่วยความจำ
    lines.push("! --- Commit Changes to Memory ---");
    lines.push("end");
    lines.push("write memory");
    lines.push("!");
    lines.push("! --- END OF AUTO-CONFIGURATION ---");

    return lines.join("\n");
}

// ส่งออกสำหรับการใช้แบบโมดูลหรือเก็บใน global
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        generateCiscoConfig
    };
} else {
    window.NetGenerator = {
        generateCiscoConfig
    };
}
